name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    # Environment variables for the build process
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      # Firebase Admin SDK credentials for server-side testing
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm test
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        # Only run if this is the main repository
        if: ${{ github.repository == 'AdityaHemanthVellanki/contexto' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          
  deploy:
    name: Deploy
    needs: build_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        # Use environment variables from the job level to avoid duplication
          
      - name: Deploy to Heroku
        # Only run deploy step on the main repo
        if: ${{ github.repository == 'AdityaHemanthVellanki/contexto' }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_TEAM: ${{ secrets.HEROKU_TEAM }}
          HEROKU_REGION: ${{ secrets.HEROKU_REGION }}
        run: |
          npm install -g heroku
          heroku container:login
          if [ -n "$HEROKU_TEAM" ]; then
            heroku create contexto-app-${{ github.run_id }} --team="$HEROKU_TEAM" --region="$HEROKU_REGION" || true
          else
            heroku create contexto-app-${{ github.run_id }} --region="$HEROKU_REGION" || true
          fi
          heroku container:push web --app contexto-app-${{ github.run_id }}
          heroku container:release web --app contexto-app-${{ github.run_id }}
